#!/bin/bash

curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
bash miniconda.sh -b -p miniconda

export PATH="$PWD/miniconda/bin:$PATH"

conda init bash

source ~/.bash_profile

conda create -n grpc_env python -y

conda activate grpc_env
pip install -r requirements.txt
